hacktoberfest2021/linked_list.cpp

Updated linked_list.cpp

---

hacktoberfest2021/Assign1_py.ipynb
hacktoberfest2021/HRA_DRA.cpp

added ds ass 1

---

hacktoberfest2021/array1.cpp
hacktoberfest2021/binary_search.cpp
hacktoberfest2021/code1.cpp

added a program

---

hacktoberfest2021/1. reduceTo1(Brute-Force).cpp
hacktoberfest2021/4. staircase.cpp
hacktoberfest2021/5. minCount(Brute-force).cpp
hacktoberfest2021/8. balancedBTs(Brute-Force).cpp

added reduce to 1 code

---

hacktoberfest2021/Count inversion using merge sort.cpp
hacktoberfest2021/recursive insertion sort.cpp

Added a code for inversion counting using merge sort

Create Count inversion using merge sort.cpp

---

hacktoberfest2021/6. countSort.cpp

countingss

---

3Sum.txt
container_with_max_vol.txt

Leetcode problem

---

hacktoberfest2021/trie.cpp

This is a code template for all the trie functions like insert, delete, search

All Trie Functions Template

---

DSA/main.py

def search(matrix, m, n, key):
i, j = 0, n - 1
while i < m and j >= 0:
if matrix[i][j] == key:
return i, j
elif key > matrix[i][j]:
i = i + 1
elif key < matrix[i][j]:
j = j - 1
return -1
if __name__ == '__main__':
t = [[0 for j in range(4)] for i in range(4)]
k = 1
for i in range(4):
for j in range(4):
t[i][j] = k
k = k+1
print(search(t, 4, 4, 13))

search_in_2d

---

Securities Buying

Harry has just started investing in stock markets. There are a variety of securities that he can buy, but he is a bit confused about buying the securities because he has a limited amount of money. The prices of the various securities are given for N days and security_value[k] denotes the price of the security on the kth day. There is one more rule, Harry can buy at most k number of securities on the kth day. As mentioned earlier, Harry has a limited amount of money with him to buy these securities and this amount is denoted by z. Can you guide Harry in finding the maximum number of securities that he can buy?

Securities Buying Question cpp

---

hacktoberfest2021/iterative merge sort.cpp

Added the code for iterative merge sort using c++. Thank you

Create iterative merge sort.cpp

---

hacktoberfest2021/Selection_Sort.cpp

The Selection Sort Code in C++ is added. The code is properly commented.

Adding Selection Sort in Cpp

---

hacktoberfest2021/Reverse_LinkedList.cpp

This is a code in **C++** programming language to **Reverse a Linked List**.
The code is properly commented and readable by any user. This will be a great add on to the already existing data structures and algorithm codes.

Added code to reverse a linked list

---

hacktoberfest2021/Two_Nodes_Distance.cpp

In a BST, I found the distance between 2 nodes using the C++ programming language.

Distance between 2 nodes in a BST

---

hacktoberfest2021/6. countSort.cpp

Code sort code in c++ language

Update 6. countSort.cpp

---

DSA/q5Karatsbusa Algo.c

Update q5Karatsbusa Algo.c

---

hacktoberfest2022/Chef and Bored Games

Create Chef and Bored Games

---

hacktoberfest2022/bubblesort in cpp

Create bubblesort in cpp

---

hacktoberfest2022/selection sort in cpp

Selection sorting algorithm in c++

selection sort in cpp

---

hacktoberfest2022/odd_even_increments.cpp

Safety Purposes

---

hacktoberfest2022/XORNEY Solution

Solution of the CodeChef problem 
Code: XORNEY
Link: https://www.codechef.com/problems/XORNEY

XORNEY Solution

---

DSA/Medians_of_medians.py

Added Median of Medians algorithm to find median of an array in O(n) time complexity.
Code in Python

Added Medians of Medians algorithm

---

hacktoberfest2022/Q11 Leetcode Max Water

Q11 Leetcode Max Water Java Solution

Q11 Leetcode Max Water

---

hacktoberfest2022/Longest_Substring.cpp
hacktoberfest2022/Merge k Sorted Lists
hacktoberfest2022/Roman_to_Integer.cpp
hacktoberfest2022/binary search.cpp

Shorter more efficient solutions

---

hacktoberfest2022/Quick_Sort.cpp

Please merge my pull request and add "hacktoberfest-accepted" tag to it.

Added Quick Sort Algorithm code

---

hacktoberfest2022/longest common prefix.cpp

longest common prefix leetcode solution

longest common prefix.cpp

---

hacktoberfest2022/Remove Nth Node From End of List

Remove Nth Node From End of List leetcode solution

Remove Nth Node From End of List

---

DSA/LongestPalindromicSubsequence.java

@projectX-india kindly accept my PR under Hacktoberfest2022

Longest Palindromic Subsequence in Java

---

hacktoberfest2022/01 knapsack bottoms up approach dp algo.cpp

Update 01 knapsack bottoms up approach dp algo.cpp
